spring:
  profiles:
    active:
      - dev

jwt:
  secret: ${JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  error:
    include-message: always

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true


server:
  error:
    include-message: always

  port: ${PORT:5000}